language: python
python:
  - "3.7-dev"

install: skip

sudo: required

branches:
  only:
    - master

services:
  - docker

before_script:
    - docker build --tag flordan/djangotest .
    - docker run $(bash <(curl -s https://codecov.io/env)) -d --name django_server flordan/djangotest
